import Head from "next/head";
import Script from "next/script";
import Layout from "../components/layout/Layout";
import { ThemeProvider } from 'next-themes'
import "../styles/globals.css";

import { wrapper } from "../store/store";

function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Wyckoff.AI</title>
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png"/>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ThemeProvider>
        <Layout>
            <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </>
  );
}

export default wrapper.withRedux(App);
