import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>A Wyckoff.ai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Landing page coming soon </h1>
        <Link href="/tools">
          <a>Navigate to Tools</a>
        </Link>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  );
}
